// Generated by gencpp from file pkg/wordsCounter.msg
// DO NOT EDIT!


#ifndef PKG_MESSAGE_WORDSCOUNTER_H
#define PKG_MESSAGE_WORDSCOUNTER_H

#include <ros/service_traits.h>


#include <pkg/wordsCounterRequest.h>
#include <pkg/wordsCounterResponse.h>


namespace pkg
{

struct wordsCounter
{

typedef wordsCounterRequest Request;
typedef wordsCounterResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct wordsCounter
} // namespace pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pkg::wordsCounter > {
  static const char* value()
  {
    return "4afd19f9b5153106d13d35f8799bf301";
  }

  static const char* value(const ::pkg::wordsCounter&) { return value(); }
};

template<>
struct DataType< ::pkg::wordsCounter > {
  static const char* value()
  {
    return "pkg/wordsCounter";
  }

  static const char* value(const ::pkg::wordsCounter&) { return value(); }
};


// service_traits::MD5Sum< ::pkg::wordsCounterRequest> should match
// service_traits::MD5Sum< ::pkg::wordsCounter >
template<>
struct MD5Sum< ::pkg::wordsCounterRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pkg::wordsCounter >::value();
  }
  static const char* value(const ::pkg::wordsCounterRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pkg::wordsCounterRequest> should match
// service_traits::DataType< ::pkg::wordsCounter >
template<>
struct DataType< ::pkg::wordsCounterRequest>
{
  static const char* value()
  {
    return DataType< ::pkg::wordsCounter >::value();
  }
  static const char* value(const ::pkg::wordsCounterRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pkg::wordsCounterResponse> should match
// service_traits::MD5Sum< ::pkg::wordsCounter >
template<>
struct MD5Sum< ::pkg::wordsCounterResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pkg::wordsCounter >::value();
  }
  static const char* value(const ::pkg::wordsCounterResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pkg::wordsCounterResponse> should match
// service_traits::DataType< ::pkg::wordsCounter >
template<>
struct DataType< ::pkg::wordsCounterResponse>
{
  static const char* value()
  {
    return DataType< ::pkg::wordsCounter >::value();
  }
  static const char* value(const ::pkg::wordsCounterResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PKG_MESSAGE_WORDSCOUNTER_H
